In [1]:
%pylab inline

Populating the interactive namespace from numpy and matplotlib


In [2]:
fdir = '/home/scratch/mabitbol/3C295/OnOff/'

In [3]:
import glob
from astropy.io import fits

In [4]:
f295 = glob.glob(fdir+'*.raw.vegas')

In [5]:
print f295

['/home/scratch/mabitbol/3C295/OnOff/scan7.raw.vegas', '/home/scratch/mabitbol/3C295/OnOff/scan8.raw.vegas', '/home/scratch/mabitbol/3C295/OnOff/scan39.raw.vegas', '/home/scratch/mabitbol/3C295/OnOff/scan40.raw.vegas', '/home/scratch/mabitbol/3C295/OnOff/scan_02_6.raw.vegas', '/home/scratch/mabitbol/3C295/OnOff/scan_02_7.raw.vegas']


In [6]:
print len(f295)

6


In [8]:
print f295[0]

/home/scratch/mabitbol/3C295/OnOff/scan7.raw.vegas


In [10]:
ls /home/scratch/mabitbol/3C295/OnOff/scan7.raw.vegas/

scan7.raw.vegas.A.fits   scan7.raw.vegas.B.index  scan7.raw.vegas.D.flag
scan7.raw.vegas.A.flag   scan7.raw.vegas.C.fits   scan7.raw.vegas.D.index
scan7.raw.vegas.A.index  scan7.raw.vegas.C.flag   scan7.raw.vegas.index
scan7.raw.vegas.B.fits   scan7.raw.vegas.C.index
scan7.raw.vegas.B.flag   scan7.raw.vegas.D.fits


In [11]:
f1 = fits.open(f295[0]+'/scan7.raw.vegas.A.fits')

In [13]:
f1[0].header

SIMPLE  =                    T / file does conform to FITS standard             
BITPIX  =                    8 / number of bits per data pixel                  
NAXIS   =                    0 / number of data axes                            
EXTEND  =                    T / FITS dataset may contain extensions            
COMMENT   FITS (Flexible Image Transport System) format is defined in 'Astronomy
COMMENT   and Astrophysics', volume 376, page 359; bibcode: 2001A&A...376..359H 
DATE    = '2017-04-04T18:12:46' / date and time this HDU was created            
ORIGIN  = 'NRAO Green Bank'    / origin of observation                          
TELESCOP= 'NRAO_GBT'           / the telescope used                             
INSTRUME= 'VEGAS   '           / backend                                        
SDFITVER= 'sdfits ver1.21'     / this file was created by sdfits                
FITSVER = '1.9     '           / FITS definition version                        

In [14]:
hdu = f1[1]

In [15]:
hdu.columns.names

['OBJECT',
 'BANDWID',
 'DATE-OBS',
 'DURATION',
 'EXPOSURE',
 'TSYS',
 'DATA',
 'TDIM7',
 'TUNIT7',
 'CTYPE1',
 'CRVAL1',
 'CRPIX1',
 'CDELT1',
 'CTYPE2',
 'CRVAL2',
 'CTYPE3',
 'CRVAL3',
 'CRVAL4',
 'OBSERVER',
 'OBSID',
 'SCAN',
 'OBSMODE',
 'FRONTEND',
 'TCAL',
 'VELDEF',
 'VFRAME',
 'RVSYS',
 'OBSFREQ',
 'LST',
 'AZIMUTH',
 'ELEVATIO',
 'TAMBIENT',
 'PRESSURE',
 'HUMIDITY',
 'RESTFREQ',
 'FREQRES',
 'EQUINOX',
 'RADESYS',
 'TRGTLONG',
 'TRGTLAT',
 'SAMPLER',
 'FEED',
 'SRFEED',
 'FEEDXOFF',
 'FEEDEOFF',
 'SUBREF_STATE',
 'SIDEBAND',
 'PROCSEQN',
 'PROCSIZE',
 'PROCSCAN',
 'PROCTYPE',
 'LASTON',
 'LASTOFF',
 'TIMESTAMP',
 'QD_XEL',
 'QD_EL',
 'QD_BAD',
 'QD_METHOD',
 'VELOCITY',
 'ZEROCHAN',
 'DOPFREQ',
 'ADCSAMPF',
 'VSPDELT',
 'VSPRVAL',
 'VSPRPIX',
 'SIG',
 'CAL',
 'CALTYPE',
 'TWARM',
 'TCOLD',
 'CALPOSITION',
 'IFNUM',
 'PLNUM',
 'FDNUM']

In [16]:
data = hdu.data['DATA']

In [22]:
data

array([[  1.34268211e+09,   2.32202656e+05,   2.40223750e+05, ...,
          2.60404172e+05,   2.62294500e+05,   2.70366656e+05],
       [  9.30549568e+08,   2.44515281e+05,   2.34910422e+05, ...,
          3.64320625e+05,   3.87157719e+05,   3.80311688e+05],
       [  1.95299226e+09,   2.37056188e+05,   2.11664609e+05, ...,
          3.28762188e+05,   3.35352750e+05,   3.43527094e+05],
       ..., 
       [             nan,              nan,              nan, ...,
                     nan,              nan,              nan],
       [  0.00000000e+00,  -2.75884351e+03,   4.29153418e+03, ...,
         -8.42979980e+03,   7.30582617e+03,  -4.39371387e+03],
       [             nan,              nan,              nan, ...,
                     nan,              nan,              nan]], dtype=float32)

In [30]:
offdata = data[::2, :]
ondata = data[1::2, :]

In [32]:
print offdata.shape
print ondata.shape

(5724, 16384)
(5724, 16384)


In [26]:
hdu.data['CAL'][::2]

chararray(['F', 'F', 'F', ..., 'F', 'F', 'F'], 
      dtype='|S1')

In [33]:
hdu.data['CAL'][1::2]

chararray(['T', 'T', 'T', ..., 'T', 'T', 'T'], 
      dtype='|S1')

In [34]:
hdu.data['PLNUM']

array([3, 3, 2, ..., 1, 0, 0], dtype=int16)

In [35]:
hdu.data['PLNUM'][::2]

array([3, 2, 1, ..., 2, 1, 0], dtype=int16)

In [36]:
hdu.data['PLNUM'][1::2]

array([3, 2, 1, ..., 2, 1, 0], dtype=int16)

In [37]:
# XX, YY, XY, YX

In [38]:
offdata = offdata.reshape((-1, 4, 16384))

In [39]:
ondata = ondata.reshape((-1, 4, 16384))

In [40]:
offdata.shape

(1431, 4, 16384)

In [41]:
xxoffdata = offdata[:,0,:]

In [42]:
xxondata = ondata[:,0,:]

In [43]:
xxoffdata.shape

(1431, 16384)

In [44]:
xxondata.shape

(1431, 16384)

In [45]:
# time, frequency

In [ ]:
xx