In [1]:
%pylab inline

Populating the interactive namespace from numpy and matplotlib


In [2]:
cd /home/mabitbol/GBT-S140/analysis/

/home/mabitbol/GBT-S140/analysis


In [3]:
import spectra as spec

In [4]:
spectrum = spec.AperturePhotometry(inside=67., outside=90.)

In [5]:
wmapflux, wmaperrs = spectrum.run_experiment(spectrum.wmapfiles)

([31.632674932479858,
  31.357146620750427,
  28.49216927587986,
  25.705389365553856,
  34.781158536672592],
 [0.88105547921204608,
  0.87757244077114571,
  0.85334168678953104,
  1.0439084274695756,
  2.0083911251101307])

In [7]:
pflux, perrs = spectrum.run_experiment(spectrum.planckfiles)

In [8]:
spectrum.planckfreqs

array([  2.84000000e+10,   4.41000000e+10,   7.04000000e+10,
         1.43000000e+11,   2.17000000e+11,   3.53000000e+11,
         5.45000000e+11,   8.57000000e+11])

In [18]:
spectrum.irisfreqs

array([  2.50000000e+13,   1.20000000e+13,   5.00000000e+12,
         3.00000000e+12])

In [17]:
spectrum.run_experiment(spectrum.irisfiles)

([1925.8985934257507,
  4156.5936050415039,
  25203.214221954346,
  52549.74577331543],
 [38.427498538743151,
  63.149274592441095,
  309.45122978572113,
  919.78777406282859])

In [19]:
spectrum.dirbefreqs

array([  2.40000000e+14,   1.36360000e+14,   8.57100000e+13,
         6.12200000e+13,   2.50000000e+13,   1.20000000e+13,
         5.00000000e+12,   3.00000000e+12,   2.14280000e+12,
         1.25000000e+12])

In [8]:
spectrum.run_experiment(spectrum.dirbefiles)

([120.82237476110458,
  157.95607751607895,
  175.49477934837341,
  187.67948943376541,
  1783.5755047798157,
  3474.6156387329102,
  24606.915657043457,
  49586.261642456055,
  80216.431091308594,
  46854.170928955078],
 [36.626654112102038,
  37.944885408187638,
  18.861293489466497,
  8.4068980969050084,
  43.295220730564232,
  52.650926164462071,
  376.87594711837153,
  1060.5722142623765,
  1963.6687910965784,
  1511.6200740315546])